

package userinterface.AdministrativeRole;

import Business.Candidate.Candidate;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.EcoSystem;
import Business.Network.Network;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultTreeModel;
import Business.DB4OUtil.DB4OUtil;
import Business.Organization.OrganizationDirectory;
import Business.Role.Role1;
import userinterface.SystemAdminWorkArea.ManageEnterpriseJPanel;
/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecosystem;
    DB4OUtil db4;
    OrganizationDirectory directory;
    /** Creates new form AdminWorkAreaJPanel
     * @param userProcessContainer
     * @param enterprise */
    //OrganizationDirectory directory;
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.db4 = DB4OUtil.getInstance();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = new Enterprise("OVS", Enterprise.EnterpriseType.OnlineVotingSystem) {
          
            @Override
            public ArrayList<Role1> getSupportedRole() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
        //this.directory=directory;
       this.ecosystem = db4.retrieveSystem();
        //populateTree();
        //valueLabel.setText(enterprise.getName());  
    }
    
      
    /*public void populateTree(){
       DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
       ArrayList<Network> networkList=ecosystem.getNetworkList();
       ArrayList<Enterprise> enterpriseList;
       ArrayList<Organization> organizationList;

       Network network;
       Enterprise enterprise;
       Organization organization;

       DefaultMutableTreeNode networks=new DefaultMutableTreeNode("Networks");
       DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
       root.removeAllChildren();
       root.insert(networks, 0);

       DefaultMutableTreeNode networkNode;
       DefaultMutableTreeNode enterpriseNode;
       DefaultMutableTreeNode organizationNode;

       for(int i=0;i<networkList.size();i++){
           network=networkList.get(i);
           networkNode=new DefaultMutableTreeNode(network.getName());
           networks.insert(networkNode, i);

           enterpriseList=network.getEnterpriseDirectory().getEnterpriseList();
           for(int j=0; j<enterpriseList.size();j++){
               enterprise=enterpriseList.get(j);
               enterpriseNode=new DefaultMutableTreeNode(enterprise.getName());
               networkNode.insert(enterpriseNode, j);

               organizationList=enterprise.getOrganizationDirectory().getOrganizationList();
               for(int k=0;k<organizationList.size();k++){
                   organization=organizationList.get(i);
                   organizationNode=new DefaultMutableTreeNode(organization.getName());
                   enterpriseNode.insert(organizationNode, k);
               }
           }
       }
       model.reload();
   }*/
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        voterbtn = new javax.swing.JButton();
        candybtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Adminstrative Role");

        voterbtn.setText("Manage Voter Information");
        voterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voterbtnActionPerformed(evt);
            }
        });

        candybtn.setText("Manage Candidate Information");
        candybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candybtnActionPerformed(evt);
            }
        });

        jButton1.setText("Manage Organization");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(voterbtn)
                            .addComponent(candybtn)
                            .addComponent(jButton1))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(candybtn)
                .addGap(30, 30, 30)
                .addComponent(voterbtn)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void candybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candybtnActionPerformed
        // TODO add your handling code here:
       ManageCandidateJPanel manageecandidateJPanel = new ManageCandidateJPanel(userProcessContainer, ecosystem);
       userProcessContainer.add("ManageCandidateJPanel",manageecandidateJPanel);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);     
    }//GEN-LAST:event_candybtnActionPerformed

    private void voterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voterbtnActionPerformed
        // TODO add your handling code here:
       ManageVoterJPanel managevoterJPanel = new ManageVoterJPanel(userProcessContainer, ecosystem);
       userProcessContainer.add("ManageVoterJPanel",managevoterJPanel);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer); 
    }//GEN-LAST:event_voterbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ManageOrganizationJPanel manageOrganizationJPanel=new ManageOrganizationJPanel(userProcessContainer,enterprise.getOrganizationDirectory());
       userProcessContainer.add("manageEnterpriseAdminJPanel",manageOrganizationJPanel);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed
/*
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton candybtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton voterbtn;
    // End of variables declaration//GEN-END:variables
    
}
